apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: mern-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: aviral2/soen-frontend:latest
        ports:
        - containerPort: 5173
        envFrom:
        - configMapRef:
            name: mern-config


