apiVersion: v1
kind: Secret
metadata:
  name: mern-secret
  namespace: mern-app
type: Opaque
stringData:
  MONGODB_URI: mongodb+srv://aviral0201:1234qwer@cluster0.bzblq.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0 # (Base64 encoded value)
